In [ ]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install scikit-learn
!pip install pathlib

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.23.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (0.12.2)
Requirement already satisfied: numpy!=1.24.0,>=1.17 in /usr/local/lib/python3.10/dist-packages (from seaborn) (1.23.5)
Requirement already satisfied: pandas>=0.25 in /usr/local/lib/python3.10/dist-packages (from seaborn) (1.5.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in /usr/local/lib/python3.10/dist-packages (from seaborn) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25->seaborn) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.16.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.23.5)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.2.0)
Requirement already satisfied: pathlib in /usr/local/lib/python3.10/dist-packages (1.0.1)

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from pathlib import Path

In [ ]:
from google.colab import files
upload = files.upload()

Saving games.csv to games.csv

In [ ]:
#melakukan preprocessing data
games = pd.read_csv('games.csv')
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              20058 non-null  object
 1   rated           20058 non-null  bool
 2   created_at      20058 non-null  float64
 3   last_move_at    20058 non-null  float64
 4   turns           20058 non-null  int64
 5   victory_status  20058 non-null  object
 6   winner          20058 non-null  object
 7   increment_code  20058 non-null  object
 8   white_id        20058 non-null  object
 9   white_rating    20058 non-null  int64
 10  black_id        20058 non-null  object
 11  black_rating    20058 non-null  int64
 12  moves           20058 non-null  object
 13  opening_eco     20058 non-null  object
 14  opening_name    20058 non-null  object
 15  opening_ply     20058 non-null  int64
dtypes: bool(1), float64(2), int64(4), object(9)
memory usage: 2.3+ MB

untuk mengecek apakah ada missing values.

In [ ]:
pd.DataFrame({'dtypes': games.dtypes, 'null_count': games.isnull().sum()}).loc[lambda x: x.null_count != 0]

Empty DataFrame
Columns: [dtypes, null_count]
Index: []

In [ ]:
#pada dataset, tidak terdapat missing values
#maka selanjutnya dapat dilakukan transformasi variabel yang mengandung non-numerikal menjadi numerikal.

# Rated = 1, Not rated = 0
games['rated_bin'] = np.where(games['rated'] == True, 1, 0)
## White = 1, Black = 0
games['winner_bin'] = np.where(games['winner'] == 'white', 1, 0)

In [ ]:
#untuk mempermudah pembacaan saat exploratory data, kolom created_at dan last_move_at ke format yang mudah dibaca

games['created_at_dt'] = pd.to_datetime(games['created_at']/1000,
                                        unit='s',
                                        origin='unix')

games['last_move_at_dt'] = pd.to_datetime(games['last_move_at']/1000,
                                          unit='s',
                                          origin='unix')

In [ ]:
games['game_len_dt'] = games['last_move_at_dt'] - games['created_at_dt'
games['game_len'] = games['last_move_at'] - games['created_at']

games['game_len_mins'] = games['game_len'].apply(lambda x: round(x / 1000 / 60, 2))

In [ ]:
#jarak rating pemain akan mengukur perbedaan absolut rating di antara pemain di permainan tertentu

games['rating_distance'] = games['white_rating'] - games['black_rating']
games['rating_distance'] = games['rating_distance'].apply(abs)

In [ ]:
print(games['victory_status'].unique())
print(pd.factorize(games['victory_status'].unique())[0])

['outoftime' 'resign' 'mate' 'draw']
[0 1 2 3]

In [ ]:
#menggunakan One Hot Encoder
ohe = OneHotEncoder(handle_unknown='error')

In [ ]:
#menetapkan kolom transformator
trans_kol = make_column_transformer((ohe,['victory_status']),
                                       remainder='passthrough')

In [ ]:
trans_kol.fit(pd.DataFrame(games['victory_status']))

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder', OneHotEncoder(),
                                 ['victory_status'])])

In [ ]:
## lakukan One-hot-encode pada variabel 'victory_status'  dan masukkan ke np.array()
hot_victory = trans_kol.transform(pd.DataFrame(games['victory_status'])).toarray()

In [ ]:
#membuat dataframe dari output transformator
VICTORY_STATUS = pd.DataFrame(hot_victory,
                             columns = trans_kol.get_feature_names_out())

In [ ]:
# me-rename kolom agar lebih jelas
VICTORY_STATUS.columns = ['victory_status_draw', 'victory_status_mate', 'victory_status_outoftime', 'victory_status_resign']

In [ ]:
# Merge hasil one-hot-encoding ke satu dataframe parent
games = games.merge(VICTORY_STATUS,
                    left_index=True,
                    right_index=True)

In [ ]:
#Sample hasil akhir dari one-hot-encoding
to_show = ['victory_status',
    'victory_status_draw',
    'victory_status_mate',
    'victory_status_outoftime',
    'victory_status_resign']

games[to_show].head(10)

,victory_status,victory_status_draw,victory_status_mate,victory_status_outoftime,victory_status_resign
0,outoftime,0.0,0.0,1.0,0.0
1,resign,0.0,0.0,0.0,1.0
2,mate,0.0,1.0,0.0,0.0
3,mate,0.0,1.0,0.0,0.0
4,mate,0.0,1.0,0.0,0.0
5,draw,1.0,0.0,0.0,0.0
6,resign,0.0,0.0,0.0,1.0
7,resign,0.0,0.0,0.0,1.0
8,resign,0.0,0.0,0.0,1.0
9,mate,0.0,1.0,0.0,0.0